#!/bin/sh
#
# Homebrew
#

#  install homebrew if not already installed
if test ! $(which brew)
then
  echo "  Installing Homebrew..."
  if test "$(uname)" = "Darwin"
  then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

# install packages
echo "› brew bundle"
brew bundle

exit 0
