#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e
echo ''

. script/_functions

setup_gitconfig
install_dotfiles
install_dependencies

echo ''
echo '  All installed!'
